/*
    Quine McCluskey Reduction Algorithm
    Author: Tennyson Demchuk
    09.17.2020
*/

#include <iostream>
#include <string>

// Function prototypes
std::string extractVars(std::string input);                     // extract all unique variables in input expression and return as reverse  sorted string
int hammingDistance(std::string imp1, std::string imp2);        // calculates hamming distance between two provided implicants
int numBitsHigh(std::string imp);                               // returns number of high bits in implicant


/*
    This program takes a boolean expression in the form of "AB + AC + B'C +...",
    calculates its truth table, then reduces the expression via Quine McCluskey
    reduction. The reduced expression is output to the console. A reduction
    report containing reduction and expression details can be generated by 
    specifying '-o OutputFileName' as an argument.
*/


int main(int argc, char* argv[]) {

    return 0;
}